import { useCallback,useEffect,useMemo,useState } from "react";
import axios from "axios";
import { api } from "../../src/lib/api";

type AdminRole="tier_1_admin"|"tier_2_admin"|"tier_3_admin"|"manager"|"executive"|"auditor"|"super_admin";
type Member={id:string;email:string;displayName:string;status:string;tenantRole:"tenant_user";platformRole:AdminRole|null;adminStatus:string|null;lastSeenAt:number};
type AuditEvent={id:string;action:string;fromRole:string|null;toRole:string|null;createdAt:number;actorName:string;targetName:string};
type Workspace={viewer:{tenantRole:"tenant_user";platformRole:AdminRole|null;tenantId:string;tenantName:string;tenantStatus:string;permissions:string[]};members:Member[];audit:AuditEvent[];correlationId:string};

const adminRoles:Array<{key:AdminRole;label:string;tier:string;scope:string;permissions:string[];tone:string}>=[
  {key:"tier_1_admin",label:"Tier 1 Admin",tier:"Tier 1",scope:"Front-line support",permissions:["Read users","Triage support","Review security events"],tone:"#e7b252"},
  {key:"tier_2_admin",label:"Tier 2 Admin",tier:"Tier 2",scope:"Technical operations",permissions:["Resolve escalations","Read integrations","Review telemetry"],tone:"#74a789"},
  {key:"tier_3_admin",label:"Tier 3 Admin",tier:"Tier 3",scope:"Platform operations",permissions:["Advanced diagnostics","Recovery operations","Manage incidents"],tone:"#5c91ac"},
  {key:"manager",label:"Manager",tier:"Management",scope:"Teams and delivery",permissions:["Manage users","Approve operations","Review security events"],tone:"#8f7ab8"},
  {key:"executive",label:"Executive",tier:"Executive",scope:"Enterprise oversight",permissions:["Portfolio visibility","Risk acceptance","Security metrics"],tone:"#c26f69"},
  {key:"auditor",label:"Auditor",tier:"Independent",scope:"Read-only assurance",permissions:["Inspect evidence","Export audit records","Security metrics"],tone:"#6f7874"},
  {key:"super_admin",label:"Super Admin",tier:"Platform",scope:"Platform-wide authority",permissions:["Manage roles and tenants","Configure platform","Recovery authority"],tone:"#17221e"}
];
const labels=Object.fromEntries(adminRoles.map(role=>[role.key,role.label])) as Record<AdminRole,string>;
const adminLabel=(role:AdminRole|null)=>role?labels[role]:"No admin tier";

export default function AccessConsole({user,signOutPath}:{user:{id:string;name:string;email:string};signOutPath:string}){
  const [workspace,setWorkspace]=useState<Workspace|null>(null);const [section,setSection]=useState<"directory"|"roles"|"audit">("directory");const [query,setQuery]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const{data}=await api.get("/access",{headers:{"Cache-Control":"no-store"}});setWorkspace(data)},[]);
  useEffect(()=>{load().catch(error=>setMessage(error.response?.data?.error??error.message))},[load]);
  const members=useMemo(()=>(workspace?.members??[]).filter(member=>`${member.displayName} ${member.email} ${adminLabel(member.platformRole)}`.toLowerCase().includes(query.toLowerCase())),[workspace,query]);
  async function updateRole(targetUserId:string,role:"tenant_user"|AdminRole){if(!workspace)return;setBusy(true);setMessage("");try{await api.patch("/access",{tenantId:workspace.viewer.tenantId,targetUserId,role});setMessage(role==="tenant_user"?"Administrative access removed; tenant membership is unchanged.":"Administrative tier updated and recorded in the security audit.");await load()}catch(cause){const error=axios.isAxiosError(cause)?cause.response?.data?.error??cause.message:"Role update failed";setMessage(error==="SELF_DEMOTION_BLOCKED"?"You cannot remove your own Super Admin assignment.":error)}setBusy(false)}
  const canManage=workspace?.viewer.permissions.includes("roles.manage")??false;
  return <main className="access-shell"><aside className="access-sidebar"><a className="access-brand" href="/"><span>EA</span><div>Enterprise<br/>Architecture</div></a><div className="tenant-chip"><small>TENANT PLANE</small><strong>{workspace?.viewer.tenantName??"Loading…"}</strong><span>{workspace?.viewer.tenantStatus??"connecting"}</span></div><nav className="access-nav" aria-label="Access workspace"><button className={section==="directory"?"active":""} onClick={()=>setSection("directory")}><span>01</span>Tenant users</button><button className={section==="roles"?"active":""} onClick={()=>setSection("roles")}><span>02</span>Admin tiers</button><button className={section==="audit"?"active":""} onClick={()=>setSection("audit")}><span>03</span>Access audit</button><a href="/security"><span>04</span>Security operations</a></nav><div className="access-principal"><div>{user.name.slice(0,1).toUpperCase()}</div><span><strong>{user.name}</strong><small>Tenant User · {workspace?adminLabel(workspace.viewer.platformRole):"Resolving admin tier…"}</small></span><a href={signOutPath}>↗</a></div></aside>
  <section className="access-main"><header className="access-header"><div><span>Supabase identity · tenant RBAC · platform administration</span><h1>{section==="directory"?"Tenant user directory":section==="roles"?"Seven administrative tiers":"Immutable access audit"}</h1></div><a href="/security">Security operations ↗</a></header>{message&&<div className="access-message" role="status">{message}<button onClick={()=>setMessage("")}>×</button></div>}
  {section==="directory"&&<><div className="access-kpis"><article><span>TENANT USERS</span><strong>{workspace?.members.length??"—"}</strong><small>identity from Supabase Auth</small></article><article><span>ADMIN TIERS</span><strong>7</strong><small>separate platform assignments</small></article><article><span>YOUR ADMIN TIER</span><strong>{workspace?adminLabel(workspace.viewer.platformRole):"—"}</strong><small>RLS-backed live decision</small></article></div><div className="access-separation"><b>Separation of authority</b><p>Every person is a tenant user. Administrative authority is an additional, independently auditable assignment—it never replaces tenant membership.</p></div><div className="directory-tools"><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search tenant users or admin assignments…"/></label><span>{members.length} user{members.length===1?"":"s"}</span></div><div className="member-table"><div className="member-row member-head"><span>Tenant user</span><span>Identity status</span><span>Separate admin tier</span><span>Last active</span></div>{members.map(member=><article className="member-row" key={member.id}><div className="member-name"><i>{member.displayName.slice(0,1).toUpperCase()}</i><span><strong>{member.displayName}</strong><small>{member.email} · Tenant User</small></span></div><span className="member-status"><i/>{member.status}</span><select aria-label={`Administrative tier for ${member.displayName}`} disabled={!canManage||busy} value={member.platformRole??"tenant_user"} onChange={event=>updateRole(member.id,event.target.value as "tenant_user"|AdminRole)}><option value="tenant_user">No admin tier</option>{adminRoles.map(role=><option value={role.key} key={role.key}>{role.label}</option>)}</select><time>{new Date(member.lastSeenAt*1000).toLocaleDateString()}</time></article>)}</div></>}
  {section==="roles"&&<><div className="access-separation"><b>Tenant users are not an admin tier</b><p>The seven cards below represent only platform administration. Client and artisan roles remain tenant-bound marketplace assignments.</p></div><div className="role-grid admin-role-grid">{adminRoles.map((role,index)=><article key={role.key} style={{"--role":role.tone} as React.CSSProperties}><header><span>{String(index+1).padStart(2,"0")}</span><i>{role.tier}</i></header><h2>{role.label}</h2><p>{role.scope}</p><ul>{role.permissions.map(permission=><li key={permission}>{permission}</li>)}</ul><footer><span>ADMINISTRATIVE</span><b>↗</b></footer></article>)}</div></>}
  {section==="audit"&&<div className="audit-panel"><div className="audit-rule"><span>IMMUTABLE ACCOUNTING</span><p>Every administrative assignment records actor, target, previous tier, new tier, tenant context, correlation ID and timestamp.</p></div>{workspace?.audit.length?workspace.audit.map(event=><article key={event.id}><span>{new Date(event.createdAt*1000).toLocaleString()}</span><div><strong>{event.actorName}</strong> changed <strong>{event.targetName}</strong></div><p>{event.fromRole?labels[event.fromRole as AdminRole]??event.fromRole:"No admin tier"} <i>→</i> {event.toRole==="tenant_user"?"No admin tier":labels[event.toRole as AdminRole]??event.toRole}</p></article>):<div className="empty-audit"><strong>No administrative changes yet</strong><p>RBAC decisions will appear here automatically.</p></div>}</div>}
  </section></main>
}
