"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { api } from "../../src/lib/api";

type Mode = "client" | "artisan";
type Workspace = { assignments: Array<{ tenantId: string; tenantName: string; tenantType: string; roleCode: string }>; requests: Array<{ id: string; title: string; discipline: string; areaLabel: string; status: string; budgetMinMinor: number; budgetMaxMinor: number }>; featureFlags: Record<string, boolean> };

const artisans = [
  { id: "a1", name: "Mokoena Plumbing Co.", initials: "MP", discipline: "Plumbing", skills: ["Geysers", "Leak repair", "Solar heating"], area: "Johannesburg North", rate: 520, jobs: 184, rating: 4.9, reviews: 142, verified: true, available: "Tomorrow", color: "#d7ec78" },
  { id: "a2", name: "Voltwise Electrical", initials: "VE", discipline: "Electrical", skills: ["C.O.C.", "Inverters", "Rewiring"], area: "Sandton & Midrand", rate: 680, jobs: 126, rating: 4.8, reviews: 97, verified: true, available: "Thu, 6 Aug", color: "#7cc8b3" },
  { id: "a3", name: "Naledi Home Works", initials: "NH", discipline: "Painting", skills: ["Interior", "Exterior", "Waterproofing"], area: "Johannesburg Metro", rate: 390, jobs: 92, rating: 4.7, reviews: 76, verified: true, available: "This week", color: "#eab778" },
  { id: "a4", name: "Khaya Craft Carpentry", initials: "KC", discipline: "Carpentry", skills: ["Cabinetry", "Doors", "Restoration"], area: "Randburg & Roodepoort", rate: 610, jobs: 68, rating: 4.9, reviews: 55, verified: true, available: "Mon, 10 Aug", color: "#c6a6d8" },
  { id: "a5", name: "Ubuntu Property Care", initials: "UP", discipline: "Plumbing", skills: ["Maintenance", "Drainage", "Emergency"], area: "Soweto & Johannesburg", rate: 450, jobs: 211, rating: 4.6, reviews: 166, verified: true, available: "Today", color: "#e49781" },
  { id: "a6", name: "Sisonke Solar & Power", initials: "SS", discipline: "Electrical", skills: ["Solar", "Backup power", "Compliance"], area: "Gauteng", rate: 750, jobs: 143, rating: 4.8, reviews: 108, verified: true, available: "Fri, 7 Aug", color: "#8eb4da" },
];

const clientNav = ["Dashboard", "Find artisans", "Shortlist", "Requests", "Quotes", "Jobs", "Invoices", "Reviews"];
const artisanNav = ["Dashboard", "Profile", "Opportunities", "Quotes", "Clients", "Jobs", "Calendar", "Time & expenses", "Invoices", "Finance", "Reviews"];

export default function MarketplaceApp({ user, signOutPath }: { user: { name: string; email: string }; signOutPath: string }) {
  const [mode, setMode] = useState<Mode>("client"); const [section, setSection] = useState("Dashboard"); const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [discipline, setDiscipline] = useState("All disciplines"); const [area, setArea] = useState(""); const [maxRate, setMaxRate] = useState(800); const [minRating, setMinRating] = useState(0); const [sort, setSort] = useState("Recommended"); const [shortlist, setShortlist] = useState<string[]>([]); const [showRequest, setShowRequest] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const { data } = await api.get("/marketplace", { headers: { "Cache-Control": "no-store" } }); setWorkspace(data); }, []);
  useEffect(() => { load().catch((e) => setNotice(e.message)); }, [load]);
  useEffect(() => { setSection("Dashboard"); }, [mode]);
  const currentTenant = workspace?.assignments.find((a) => a.roleCode === (mode === "client" ? "user_client" : "user_artisan"));
  const results = useMemo(() => artisans.filter((a) => (discipline === "All disciplines" || a.discipline === discipline) && (!area || a.area.toLowerCase().includes(area.toLowerCase())) && a.rate <= maxRate && a.rating >= minRating).sort((a, b) => sort === "Highest rated" ? b.rating - a.rating : sort === "Most completed jobs" ? b.jobs - a.jobs : sort === "Lowest hourly rate" ? a.rate - b.rate : b.rating * b.jobs - a.rating * a.jobs), [discipline, area, maxRate, minRating, sort]);
  const nav = mode === "client" ? clientNav : artisanNav;

  function switchMode(next: Mode) { setMode(next); setNotice(`Active context changed to ${next === "client" ? "Client" : "Artisan"}. Tenant boundaries remain enforced.`); }
  function toggleShortlist(id: string) { setShortlist((items) => items.includes(id) ? items.filter((x) => x !== id) : [...items, id]); }

  return <main className="mp-shell">
    <aside className="mp-sidebar">
      <a href="/" className="mp-brand"><span>F</span><strong>FIXIT</strong><small>governed marketplace</small></a>
      <div className="mode-switch" aria-label="Active role"><button className={mode === "client" ? "active" : ""} onClick={() => switchMode("client")}>Client</button><button className={mode === "artisan" ? "active" : ""} onClick={() => switchMode("artisan")}>Artisan</button></div>
      <div className="mp-tenant"><span>ACTIVE TENANT</span><strong>{currentTenant?.tenantName ?? "Preparing workspace…"}</strong><small>{mode === "client" ? "user_client" : "user_artisan"} · ZA</small></div>
      <nav className="mp-nav">{nav.map((item, index) => <button key={item} className={section === item ? "active" : ""} onClick={() => setSection(item)}><span>{String(index + 1).padStart(2, "0")}</span>{item}{item === "Shortlist" && shortlist.length > 0 && <b>{shortlist.length}</b>}</button>)}</nav>
      <div className="mp-user"><i>{user.name.slice(0, 1).toUpperCase()}</i><span><strong>{user.name}</strong><small>{user.email}</small></span><a href={signOutPath}>↗</a></div>
    </aside>
    <section className="mp-main">
      <header className="mp-header"><div><span>{mode === "client" ? "Client workspace" : "Artisan business workspace"}</span><h1>{section}</h1></div><div><a href="/access">Access governance</a><button onClick={() => mode === "client" ? setShowRequest(true) : setSection("Opportunities")}>{mode === "client" ? "+ New service request" : "View opportunities →"}</button></div></header>
      {notice && <div className="mp-notice" role="status">{notice}<button onClick={() => setNotice("")}>×</button></div>}

      {mode === "client" && section === "Dashboard" && <ClientDashboard requests={workspace?.requests ?? []} onFind={() => setSection("Find artisans")} onRequest={() => setShowRequest(true)} />}
      {mode === "client" && section === "Find artisans" && <><div className="directory-heading"><div><span>VERIFIED ARTISAN DIRECTORY</span><h2>Find the right craft for the job.</h2><p>Public-safe profiles only. Exact addresses and private records stay protected.</p></div><div className="directory-count"><strong>{results.length}</strong><span>matching artisans</span></div></div><div className="artisan-layout"><Filters discipline={discipline} setDiscipline={setDiscipline} area={area} setArea={setArea} maxRate={maxRate} setMaxRate={setMaxRate} minRating={minRating} setMinRating={setMinRating} reset={() => { setDiscipline("All disciplines"); setArea(""); setMaxRate(800); setMinRating(0); }} /><div><div className="result-tools"><span>{results.length} results · Johannesburg & surrounds</span><select value={sort} onChange={(e) => setSort(e.target.value)}><option>Recommended</option><option>Highest rated</option><option>Most completed jobs</option><option>Lowest hourly rate</option></select></div><div className="artisan-grid">{results.map((artisan) => <ArtisanCard artisan={artisan} saved={shortlist.includes(artisan.id)} key={artisan.id} onSave={() => toggleShortlist(artisan.id)} onRequest={() => { setShowRequest(true); setNotice(`${artisan.name} will be invited when you publish the request.`); }} />)}</div>{results.length === 0 && <div className="no-results"><strong>No artisans match every filter</strong><p>Try increasing the rate range or clearing the area filter.</p><button onClick={() => { setDiscipline("All disciplines"); setArea(""); setMaxRate(800); setMinRating(0); }}>Reset filters</button></div>}</div></div></>}
      {mode === "client" && section === "Shortlist" && <Collection title="Your artisan shortlist" subtitle="Compare trusted providers before requesting a quote." items={artisans.filter((a) => shortlist.includes(a.id)).map((a) => ({ title: a.name, meta: `${a.discipline} · ${a.area}`, value: `R${a.rate}/hr · ★ ${a.rating}` }))} empty="Save artisans from the directory to compare them here." />}
      {mode === "client" && section === "Requests" && <Collection title="Service requests" subtitle="Governed requests move from draft through matching, award and job conversion." items={(workspace?.requests ?? []).map((r) => ({ title: r.title, meta: `${r.discipline} · ${r.areaLabel}`, value: `${r.status} · R${Math.round(r.budgetMinMinor / 100).toLocaleString()}–R${Math.round(r.budgetMaxMinor / 100).toLocaleString()}` }))} empty="Create your first service request to begin matching." />}
      {mode === "client" && ["Quotes", "Jobs", "Invoices", "Reviews"].includes(section) && <ClientModule section={section} />}
      {mode === "artisan" && <ArtisanWorkspace section={section} name={user.name} />}
    </section>
    {showRequest && <RequestDialog close={() => setShowRequest(false)} created={async () => { setShowRequest(false); setSection("Requests"); setNotice("Service request published with an audit correlation ID."); await load(); }} />}
  </main>;
}

function ClientDashboard({ requests, onFind, onRequest }: { requests: Workspace["requests"]; onFind: () => void; onRequest: () => void }) { return <><section className="welcome-panel"><div><span>GOOD MORNING</span><h2>What needs fixing today?</h2><p>Find verified local artisans, compare transparent quotations and keep every job accountable from appointment to review.</p><div><button onClick={onFind}>Find an artisan →</button><button onClick={onRequest}>Create a request</button></div></div><div className="welcome-orbit"><i>F</i><span>Search</span><span>Quote</span><span>Appoint</span><span>Verify</span></div></section><div className="mp-kpis"><article><span>ACTIVE REQUESTS</span><strong>{requests.filter((r) => !["closed", "cancelled"].includes(r.status)).length}</strong><small>tenant-scoped</small></article><article><span>QUOTES TO REVIEW</span><strong>3</strong><small>2 received today</small></article><article><span>ACTIVE JOBS</span><strong>2</strong><small>1 awaiting approval</small></article><article><span>OUTSTANDING</span><strong>R 8,450</strong><small>2 invoices</small></article></div><section className="activity-board"><div><span>ACTIVE WORK</span><h3>Current engagements</h3></div><article><i style={{ background: "#d7ec78" }}>PL</i><div><strong>Guest bathroom renovation</strong><small>Mokoena Plumbing Co. · Job FX-2408</small></div><span>Milestone 2 of 4</span><progress value="56" max="100" /></article><article><i style={{ background: "#8eb4da" }}>EL</i><div><strong>Backup power installation</strong><small>Sisonke Solar & Power · Job FX-2412</small></div><span>Awaiting client</span><progress value="78" max="100" /></article></section></> }

function Filters(props: { discipline: string; setDiscipline: (x: string) => void; area: string; setArea: (x: string) => void; maxRate: number; setMaxRate: (x: number) => void; minRating: number; setMinRating: (x: number) => void; reset: () => void }) { return <aside className="filters"><header><strong>Filter artisans</strong><button onClick={props.reset}>Reset</button></header><label><span>Area</span><input value={props.area} onChange={(e) => props.setArea(e.target.value)} placeholder="City, suburb or region" /></label><label><span>Discipline</span><select value={props.discipline} onChange={(e) => props.setDiscipline(e.target.value)}><option>All disciplines</option><option>Plumbing</option><option>Electrical</option><option>Painting</option><option>Carpentry</option></select></label><label><span>Maximum hourly rate</span><strong>R{props.maxRate}/hr</strong><input type="range" min="300" max="800" step="50" value={props.maxRate} onChange={(e) => props.setMaxRate(Number(e.target.value))} /></label><fieldset><legend>Minimum rating</legend>{[0, 4.5, 4.8].map((rating) => <label key={rating}><input type="radio" name="rating" checked={props.minRating === rating} onChange={() => props.setMinRating(rating)} />{rating === 0 ? "Any rating" : `★ ${rating} and above`}</label>)}</fieldset><div className="privacy-note"><b>⌾ Privacy-safe search</b><p>Only general service areas are shown. Exact addresses remain private.</p></div></aside> }

function ArtisanCard({ artisan: a, saved, onSave, onRequest }: { artisan: typeof artisans[number]; saved: boolean; onSave: () => void; onRequest: () => void }) { return <article className="artisan-card"><header><i style={{ background: a.color }}>{a.initials}</i><button onClick={onSave} aria-label={saved ? "Remove from shortlist" : "Add to shortlist"}>{saved ? "♥" : "♡"}</button></header><div className="verified">✓ VERIFIED BUSINESS</div><h3>{a.name}</h3><p>{a.discipline} · {a.area}</p><div className="skill-tags">{a.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><div className="artisan-stats"><div><strong>★ {a.rating}</strong><small>{a.reviews} reviews</small></div><div><strong>{a.jobs}</strong><small>jobs completed</small></div><div><strong>R{a.rate}</strong><small>per hour</small></div></div><footer><span><i />{a.available}</span><button onClick={onRequest}>Request quote</button></footer></article> }

function Collection({ title, subtitle, items, empty }: { title: string; subtitle: string; items: Array<{ title: string; meta: string; value: string }>; empty: string }) { return <section className="collection"><header><span>TENANT WORKSPACE</span><h2>{title}</h2><p>{subtitle}</p></header>{items.length ? <div className="collection-list">{items.map((item, i) => <article key={`${item.title}${i}`}><span>{String(i + 1).padStart(2, "0")}</span><div><strong>{item.title}</strong><small>{item.meta}</small></div><b>{item.value}</b><i>↗</i></article>)}</div> : <div className="collection-empty"><strong>Nothing here yet</strong><p>{empty}</p></div>}</section> }

function ClientModule({ section }: { section: string }) { const content: Record<string, Array<{ title: string; meta: string; value: string }>> = { Quotes: [{ title: "Guest bathroom renovation", meta: "3 comparable quotations · Same governed scope", value: "R18,400–R24,900" }, { title: "Garden lighting repair", meta: "Quote Q-1042 · Expires in 3 days", value: "R3,850" }], Jobs: [{ title: "Guest bathroom renovation", meta: "In progress · Milestone 2 of 4", value: "56%" }, { title: "Backup power installation", meta: "Awaiting client approval", value: "78%" }], Invoices: [{ title: "INV-2026-041", meta: "Mokoena Plumbing Co. · Due 12 Aug", value: "R5,200 due" }, { title: "INV-2026-038", meta: "Sisonke Solar & Power · Paid", value: "R12,800 paid" }], Reviews: [{ title: "Interior repaint", meta: "Verified completed job · Naledi Home Works", value: "★ 4.8" }] }; return <Collection title={section} subtitle={section === "Quotes" ? "Compare scope, price, validity and evidence before appointing." : `Your governed ${section.toLowerCase()} workspace.`} items={content[section]} empty={`No ${section.toLowerCase()} yet.`} /> }

function ArtisanWorkspace({ section, name }: { section: string; name: string }) { if (section === "Dashboard") return <><section className="artisan-welcome"><div><span>ARTISAN BUSINESS MODE</span><h2>Good work.<br />Clear numbers.</h2><p>Manage opportunities, jobs, evidence and cash flow from one accountable workspace.</p></div><div className="finance-hero"><span>AVAILABLE CASH</span><strong>R 42,680</strong><small>Collected this month · ZAR</small><div><b>+18.4%</b> from last month</div></div></section><div className="mp-kpis"><article><span>QUOTED PIPELINE</span><strong>R 86,200</strong><small>6 active quotes</small></article><article><span>WORK IN PROGRESS</span><strong>R 58,400</strong><small>4 active jobs</small></article><article><span>RECEIVABLES</span><strong>R 21,350</strong><small>R4,200 overdue</small></article><article><span>GROSS MARGIN</span><strong>38.6%</strong><small>rolling 90 days</small></article></div><section className="artisan-board"><header><div><span>THIS WEEK</span><h3>Jobs in motion</h3></div><button>Open job board ↗</button></header>{[{n:"01",t:"Bathroom renovation",c:"A Household",s:"In progress",v:"R24,900"},{n:"02",t:"Geyser replacement",c:"M. Dlamini",s:"Scheduled",v:"R8,750"},{n:"03",t:"Leak assessment",c:"Cornerstone Offices",s:"Awaiting client",v:"R2,400"}].map((job)=><article key={job.n}><span>{job.n}</span><div><strong>{job.t}</strong><small>{job.c}</small></div><i>{job.s}</i><b>{job.v}</b></article>)}</section></>; const datasets: Record<string, Array<{ title: string; meta: string; value: string }>> = { Profile: [{title:`${name} Artisan Services`,meta:"Draft profile · Verification pending",value:"72% complete"}], Opportunities: [{title:"Kitchen plumbing upgrade",meta:"Johannesburg North · Published 2h ago",value:"Budget R12k–R18k"},{title:"Emergency pipe repair",meta:"Randburg · Direct invitation",value:"Respond by 17:00"}], Quotes: [{title:"Q-2026-044 · Bathroom renovation",meta:"Viewed by client · Valid 5 days",value:"R24,900"}], Clients: [{title:"A Household",meta:"2 active jobs · Last contact today",value:"R5,200 due"}], Jobs: [{title:"Bathroom renovation",meta:"In progress · 18.5 hours logged",value:"38% margin"}], Calendar: [{title:"Geyser replacement",meta:"6 Aug · 08:00–12:00",value:"Confirmed"}], "Time & expenses": [{title:"This week",meta:"31.5 billable hours · R6,420 expenses",value:"R18,760 billable"}], Invoices: [{title:"INV-2026-041",meta:"Issued · Due 12 Aug",value:"R5,200"}], Finance: [{title:"August performance",meta:"Revenue R48,900 · Direct cost R29,800",value:"39.1% margin"}], Reviews: [{title:"Verified review trend",meta:"108 reviews · 143 completed jobs",value:"★ 4.8"}] }; return <Collection title={section} subtitle="Tenant-authorized operational records with immutable financial and job history." items={datasets[section] ?? []} empty={`No ${section.toLowerCase()} data yet.`} /> }

function RequestDialog({ close, created }: { close: () => void; created: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    try { await api.post("/marketplace", Object.fromEntries(new FormData(event.currentTarget))); await created(); }
    catch (cause) { setError(axios.isAxiosError(cause) ? cause.response?.data?.error ?? cause.message : "Request creation failed"); setBusy(false); }
  }
  return <div className="dialog-backdrop" role="presentation"><form className="request-dialog" onSubmit={submit}><header><div><span>NEW SERVICE REQUEST</span><h2>Describe the work</h2></div><button type="button" onClick={close}>×</button></header><label>Request title<input name="title" required minLength={5} placeholder="e.g. Guest bathroom plumbing repair" /></label><div className="form-pair"><label>Discipline<select name="discipline"><option value="plumbing">Plumbing</option><option value="electrical">Electrical</option><option value="painting">Painting</option><option value="carpentry">Carpentry</option></select></label><label>General area<input name="areaLabel" required placeholder="e.g. Randburg" /></label></div><label>Scope description<textarea name="description" required minLength={10} rows={4} placeholder="Describe the required outcome, access constraints and timing…" /></label><div className="form-pair"><label>Minimum budget (ZAR)<input name="budgetMin" type="number" min="0" defaultValue="2000" /></label><label>Maximum budget (ZAR)<input name="budgetMax" type="number" min="0" defaultValue="10000" /></label></div><div className="dialog-rule"><b>Privacy by design</b><p>Only the general area is used for matching. Share an exact address after appointment.</p></div>{error && <p className="form-error">{error}</p>}<footer><button type="button" onClick={close}>Cancel</button><button disabled={busy}>{busy ? "Publishing…" : "Publish request →"}</button></footer></form></div>;
}
