import{useCallback,useEffect,useState}from"react";
import axios from"axios";
import{api}from"./lib/api";

type FinanceData={tenantId:string;periodStart:string;periodEnd:string;currency:string;summary:{revenueMinor:number;expensesMinor:number;profitMinor:number;assetsMinor:number;liabilitiesMinor:number;equityMinor:number};accounts:Array<{code:string;name:string;type:string;balanceMinor:number}>;jobs:Array<{jobId:string;jobNumber?:string;title?:string;revenueMinor:number;costsMinor:number;marginMinor:number}>;evidence:{postedEntries:number;unreconciledEntries:number};profile:{legal_form:string;reporting_framework:string;reporting_currency:string;financial_year_end_month:number;vat_registered:boolean;review_status:string};expenses:Array<{id:string;expense_date:string;supplier_name?:string;description:string;amount_minor:number;account_code:string;evidence_status:string}>;disclaimer:string};
type Commentary={headline:string;summary:string;strengths:string[];risks:string[];actions:string[];accountantReview:string};
const money=(minor:number=0)=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:0}).format(minor/100);
const today=new Date().toISOString().slice(0,10);const yearStart=`${new Date().getFullYear()}-01-01`;

export default function FinanceConsole({user,signOutPath}:{user:{name:string;email:string};signOutPath:string}){
 const[data,setData]=useState<FinanceData|null>(null);const[start,setStart]=useState(yearStart);const[end,setEnd]=useState(today);const[section,setSection]=useState<"overview"|"ledger"|"record">("overview");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[commentary,setCommentary]=useState<Commentary|null>(null);
 const load=useCallback(async()=>{try{const{data}=await api.get("/finance",{params:{start,end}});setData(data);setMessage("")}catch(cause){setMessage(axios.isAxiosError(cause)?cause.response?.data?.error??cause.message:"Finance unavailable")}},[start,end]);useEffect(()=>{load()},[load]);
 async function post(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");try{const values=Object.fromEntries(new FormData(event.currentTarget));await api.post("/finance",values);setMessage("Balanced journal posted successfully.");event.currentTarget.reset();await load();setSection("overview")}catch(cause){setMessage(axios.isAxiosError(cause)?cause.response?.data?.error??cause.message:"Posting failed")}setBusy(false)}
 async function explain(){setBusy(true);setMessage("");try{const{data}=await api.post("/finance-ai",{start,end});setCommentary(data.commentary)}catch(cause){setMessage(axios.isAxiosError(cause)?cause.response?.data?.error??cause.message:"AI commentary unavailable")}setBusy(false)}
 const s=data?.summary;
 return <main className="fin-shell"><aside className="fin-sidebar"><a href="/marketplace" className="mp-brand"><span>F</span><strong>FIXIT FINANCE</strong><small>management accounts</small></a><div className="fin-entity"><small>ARTISAN BUSINESS</small><strong>{user.name} Artisan Services</strong><span>{data?.profile.reporting_framework.replaceAll("_"," ").toUpperCase()??"INITIALISING LEDGER"}</span></div><nav><button className={section==="overview"?"active":""} onClick={()=>setSection("overview")}>01 · Management accounts</button><button className={section==="ledger"?"active":""} onClick={()=>setSection("ledger")}>02 · Ledger & evidence</button><button className={section==="record"?"active":""} onClick={()=>setSection("record")}>03 · Record transaction</button><a href="/marketplace">04 · Marketplace</a><a href="/security">05 · Security</a></nav><div className="fin-user"><b>{user.name}</b><small>{user.email}</small><a href={signOutPath}>Sign out ↗</a></div></aside><section className="fin-main"><header><div><span>IFRS-ALIGNED ARTISAN FINANCE</span><h1>{section==="overview"?"Management accounts":section==="ledger"?"Ledger and evidence":"Record financial activity"}</h1></div><div className="fin-period"><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div></header>{message&&<div className="fin-message">{message}<button onClick={()=>setMessage("")}>×</button></div>}
 {section==="overview"&&<><div className="fin-assurance"><div><span>REPORT STATUS</span><b>{data?.profile.review_status.replaceAll("_"," ")??"unreviewed"}</b></div><p>Platform-generated management accounts · Double-entry ledger · {data?.evidence.postedEntries??0} posted journals · {data?.evidence.unreconciledEntries??0} awaiting reconciliation</p><i>{data?.profile.vat_registered?"VAT REGISTERED":"NOT VAT REGISTERED"}</i></div><div className="fin-kpis"><article><span>REVENUE</span><strong>{money(s?.revenueMinor)}</strong><small>recognised in period</small></article><article><span>OPERATING COSTS</span><strong>{money(s?.expensesMinor)}</strong><small>ledger-derived expenses</small></article><article className={(s?.profitMinor??0)>=0?"positive":"negative"}><span>NET RESULT</span><strong>{money(s?.profitMinor)}</strong><small>{(s?.revenueMinor??0)>0?`${Math.round(((s?.profitMinor??0)/(s?.revenueMinor??1))*100)}% margin`:"no revenue posted"}</small></article><article><span>NET ASSETS</span><strong>{money((s?.assetsMinor??0)-(s?.liabilitiesMinor??0))}</strong><small>assets less liabilities</small></article></div><section className="fin-grid"><div className="fin-statement"><header><span>INCOME STATEMENT</span><b>{start} — {end}</b></header><div className="statement-row total"><span>Service revenue</span><strong>{money(s?.revenueMinor)}</strong></div>{data?.accounts.filter(a=>a.type==="expense").map(a=><div className="statement-row" key={a.code}><span>{a.code} · {a.name}</span><strong>({money(a.balanceMinor)})</strong></div>)}<div className="statement-row result"><span>Net profit / (loss)</span><strong>{money(s?.profitMinor)}</strong></div><footer>{data?.disclaimer}</footer></div><aside className="fin-ai"><span>AI MANAGEMENT COMMENTARY</span>{commentary?<><h2>{commentary.headline}</h2><p>{commentary.summary}</p><h3>Recommended actions</h3><ol>{commentary.actions.map(item=><li key={item}>{item}</li>)}</ol><div>{commentary.accountantReview}</div></>:<><h2>Understand the numbers.</h2><p>Generate plain-language commentary using only these ledger aggregates. AI cannot post journals, change tax status or claim assurance.</p><button disabled={busy||!data} onClick={explain}>{busy?"Analysing…":"Generate commentary →"}</button></>}</aside></section><section className="job-profit"><header><div><span>JOB COSTING</span><h2>Profitability by job</h2></div><button onClick={()=>setSection("record")}>Record activity +</button></header>{data?.jobs.length?data.jobs.map(job=><article key={job.jobId}><span>{job.jobNumber??"JOB"}</span><div><strong>{job.title??"Linked job"}</strong><small>Revenue {money(job.revenueMinor)} · Costs {money(job.costsMinor)}</small></div><b>{money(job.marginMinor)}</b></article>):<div className="fin-empty">Link invoices and expenses to jobs to build a profitability history.</div>}</section></>}
 {section==="ledger"&&<><div className="fin-kpis compact"><article><span>POSTED JOURNALS</span><strong>{data?.evidence.postedEntries??0}</strong></article><article><span>AWAITING RECONCILIATION</span><strong>{data?.evidence.unreconciledEntries??0}</strong></article><article><span>ASSURANCE</span><strong>{data?.profile.review_status.replaceAll("_"," ")??"—"}</strong></article></div><div className="ledger-table"><header><span>Date</span><span>Source</span><span>Description</span><span>Amount</span><span>Evidence</span></header>{data?.expenses.length?data.expenses.map(expense=><article key={expense.id}><time>{expense.expense_date}</time><span>{expense.account_code}</span><div><strong>{expense.description}</strong><small>{expense.supplier_name??"No supplier recorded"}</small></div><b>{money(expense.amount_minor)}</b><i>{expense.evidence_status.replaceAll("_"," ")}</i></article>):<div className="fin-empty">No expense evidence has been posted for this artisan.</div>}</div></>}
 {section==="record"&&<form className="fin-entry" onSubmit={post}><span>CONTROLLED JOURNAL ENTRY</span><h2>Record business activity</h2><p>Fixit generates the balanced debit and credit lines. Posted transactions are immutable and corrected through reversals.</p><div className="form-pair"><label>Transaction type<select name="action" required><option value="invoice">Customer invoice</option><option value="payment">Customer payment</option><option value="expense">Business expense</option><option value="contribution">Owner contribution</option></select></label><label>Date<input name="date" type="date" defaultValue={today} required/></label></div><div className="form-pair"><label>Amount (ZAR)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Expense account<select name="accountCode"><option value="5000">Direct materials</option><option value="5100">Direct labour</option><option value="5200">Subcontractors</option><option value="6000">Vehicle and travel</option><option value="6100">Tools and equipment</option><option value="6200">Platform and payment fees</option><option value="6900">Other operating expenses</option></select></label></div><label>Description<input name="description" minLength={3} placeholder="What happened and why?" required/></label><div className="form-pair"><label>Supplier / customer reference<input name="supplierName" placeholder="Optional counterparty"/></label><label>Evidence reference<input name="evidenceReference" placeholder="Receipt, invoice or bank reference"/></label></div><div className="entry-warning"><b>Human confirmation required</b><p>By posting, you confirm that the amount and business purpose reflect a real transaction. This is not tax or accounting advice.</p></div><button disabled={busy}>{busy?"Posting balanced journal…":"Post transaction →"}</button></form>}
 </section></main>
}
